package com.aibert.dosw.domain.model.user;

public enum Career {
    INGENIERIA_SISTEMAS,
    INGENIERIA_CIVIL,
    INGENIERIA_ELECTRICA,
    INGENIERIA_ELECTRONICA,
    INGENIERIA_INDUSTRIAL,
    INGENIERIA_MECANICA,
    INGENIERIA_BIOMEDICA,
    MATEMATICAS,
    FISICA,
    ADMINISTRACION_EMPRESAS
}
